version: '3.8'
services:
  db:
    image: postgres:12
    container_name: private-postgresdb
    environment:
        - POSTGRES_USER=${POSTGRESQL_USER}
        - POSTGRES_PASSWORD=${POSTGRESQL_PASS}
        - POSTGRES_DB=${POSTGRESQL_DB}
    ports:
      - ${POSTGRESQL_PORT}:5432
    volumes: 
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local