version: '3.9'

services:
#---------------------------------------------------------
    postgresdb:        
        image: postgres:12
        container_name: private-postgresdb
        #command: ["postgres", "-c", "log_statement=all"] #enable docker console query logs
        environment:
            - POSTGRES_USER=${POSTGRESQL_USER}
            - POSTGRES_PASSWORD=${POSTGRESQL_PASS}
            - POSTGRES_DB=${POSTGRESQL_DB}
        ports:
            - ${POSTGRESQL_PORT}:5432
        volumes:
            - postgresdata:/var/lib/postgresql/data          
        networks:
            - private-default
               
#---------------------------------------------------------
networks:
    local-default:
        name: private-ext-network